name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  publish-and-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump to next dev version
        if: ${{ success() }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm version prepatch --preid=dev
          git push origin HEAD:main --follow-tags
